apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: escalado-r1
  namespace: so1p2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  ruta1

  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
