apiVersion: apps/v1 
kind: Deployment 
metadata:     
  name: py-deployment         
  namespace: so1p2   
  labels:             
    app: py-app              
spec:                          
  replicas: 1    
  selector:                    
    matchLabels:                 
      app: py-app             
  template:                     
    metadata:                 
      labels:                    
        app: py-app          
    spec:           
      containers:
      - name: py-app
        image: josemore99/py_so1
        ports:
        - containerPort: 3000

--- 
apiVersion: v1
kind: Service
metadata:
  name: py-app
  namespace: so1p2
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: py-app
  type: NodePort