
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisdb
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: redisdb
  template:
    metadata:
      labels:
        app: redisdb
    spec:
      containers:
        - name: redis
          image: redis:latest 
          ports:
            - containerPort: 6379 
---
apiVersion: v1
kind: Service
metadata:
  name: servicio-redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379 
  type: LoadBalancer 
