apiVersion: apps/v1  
kind: Deployment    
metadata:               
  name: nodeapi
  namespace: so1p2
  labels:                              
    app: nodeapi
spec:    
  replicas: 1    
  selector:  
    matchLabels:                 
      app: nodeapi
  template:
    metadata:
      labels:                    
        app: nodeapi
    spec: 
      containers:
      - name: nodeapi
        image: josemore99/apinodeso1
        ports:                  
        - containerPort: 4000 
        env:
        - name: DB_RED_HOST
          value: "35.224.254.166"
        - name: DB_RED_PORT
          value: "6379"
        - name: DB_key
          value: "Clave"
        - name: DB_MY_USER
          value: "root"
        - name: DB_MY_PASSWORD
          value: "d4d202a70b"
        - name: DB_MY_HOST
          value: "34.29.199.68"
        - name: DB_MY_PORT
          value: "3306"
        - name: DB_MY_NAME
          value: "Dbsopes"

---
apiVersion: v1
kind: Service
metadata:
  name: servicio-apinode
  namespace: so1p2
spec:
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: nodeapi
  type: LoadBalancer